<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OpenApiGenerateDocumentsOnBuild>false</OpenApiGenerateDocumentsOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Supabase" Version="1.1.1"/>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7"/>
  </ItemGroup>
</Project>